optimizer:
  type: AdamW
  kwargs:
    lr: 1e-4
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 100
    initial_epochs: 10

dataset:
  train:
    _base_: ReConV2/cfgs/dataset_configs/HybridLabeled.yaml
    others:
      subset: 'train'
      npoints: 1024
  val:
    _base_: ReConV2/cfgs/dataset_configs/HybridLabeled.yaml
    others:
      subset: 'test'
      npoints: 1024

model:
  NAME: PointTransformer
  embed_dim: 384
  depth: 12
  drop_path_rate: 0.2
  cls_dim: 87
  num_heads: 6
  group_size: 32
  num_group: 64
  with_color: FALSE
  img_views: 10


npoints: 1024
total_bs: 128
step_per_update: 1
max_epoch: 100
grad_norm_clip: 10
