optimizer:
  type: AdamW
  kwargs:
    lr: 5e-5
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 300
    initial_epochs: 10

dataset:
  train:
    _base_: ReConV2/cfgs/dataset_configs/Hybrid.yaml
    others:
      subset: train
      npoints: 1024

model:
  NAME: ReCon2
  group_size: 32
  num_group: 64
  mask_ratio: 0.7
  mask_type: causal
  embed_dim: 1024
  depth: 24
  drop_path_rate: 0.1
  num_heads: 16
  decoder_depth: 4
  with_color: False
  stop_grad: True
  large_embedding: True
  img_queries: 10
  text_queries: 1
  contrast_type: byol
  pretrained_model_name: eva_large_patch14_336.in22k_ft_in22k_in1k

npoints: 1024
total_bs: 512
step_per_update: 1
max_epoch: 300
