optimizer:
  type: AdamW
  kwargs:
    lr: 5e-5
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 300
    initial_epochs: 10

dataset:
  train:
    _base_: ReConV2/cfgs/dataset_configs/OpenShape.yaml
    others:
      subset: train
      npoints: 1024
      rgb_random_drop_prob: 0.5
      occlusion: False

model:
  NAME: ReCon2
  group_size: 32
  num_group: 64
  mask_ratio: 0.7
  mask_type: causal
  embed_dim: 1024
  depth: 24
  drop_path_rate: 0.1
  num_heads: 16
  decoder_depth: 4
  with_color: False
  stop_grad: True
  large_embedding: True
  img_queries: 13
  text_queries: 3
  contrast_type: byol
  pretrained_model_name: eva_large_patch14_336.in22k_ft_in22k_in1k
#  pretrained_model_name: vit_large_patch14_clip_336.openai
#  pretrained_model_name: vit_large_patch14_reg4_dinov2.lvd142m

modelnet40:
  test_split: ReConV2/data/openshape/meta_data/modelnet40/test_split.json
  test_pc: ReConV2/data/openshape/meta_data/modelnet40/test_pc.npy
  clip_feat_path: ReConV2/data/openshape/meta_data/modelnet40/cat_name_pt_feat.npy
  num_workers: 8
  batch_size: 128
  ratio: 0.5

objaverse_lvis:
  split: ReConV2/data/openshape/meta_data/split/lvis.json
  clip_feat_path: ReConV2/data/openshape/meta_data/lvis_cat_name_pt_feat.npy
  num_workers: 8
  batch_size: 128
  ratio: 0.5

scanobjectnn:
  data_path: ReConV2/data/openshape/meta_data/scanobjectnn/xyz_label.npy
  clip_feat_path: ReConV2/data/openshape/meta_data/scanobjectnn/cat_name_pt_feat.npy
  num_workers: 8
  batch_size: 128
  ratio: 0.3

npoints: 1024
total_bs: 512
step_per_update: 1
max_epoch: 300
