optimizer:
  type: AdamW
  kwargs:
    lr: 0.00002
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 200
    initial_epochs: 10

dataset:
  train:
    _base_: ReConV2/cfgs/dataset_configs/OpenShape.yaml
    others:
      subset: 'train'
      npoints: 10000
      rgb_random_drop_prob: 0.5
      occlusion: False

model:
  NAME: ReCon2
  group_size: 32
  num_group: 512
  mask_ratio: 0.7
  mask_type: rand
  embed_dim: 1408
  depth: 40

  drop_path_rate: 0.1
  num_heads: 16
  decoder_depth: 4
  with_color: True
  stop_grad: True
  large_embedding: False
  img_queries: 13
  text_queries: 3
  contrast_type: 'byol'
  pretrained_model_name: 'vit_giant_patch14_clip_224.laion2b'

modelnet40:
  test_split: ReConV2/data/openshape/meta_data/modelnet40/test_split.json
  test_pc: ReConV2/data/openshape/meta_data/modelnet40/test_pc.npy
  clip_feat_path: ReConV2/data/openshape/meta_data/modelnet40/cat_name_pt_feat.npy
  num_workers: 8
  batch_size: 128
  ratio: 0.5

objaverse_lvis:
  split: ReConV2/data/openshape/meta_data/split/lvis.json
  clip_feat_path: ReConV2/data/openshape/meta_data/lvis_cat_name_pt_feat.npy
  num_workers: 8
  batch_size: 128
  ratio: 0.5

scanobjectnn:
  data_path: ReConV2/data/openshape/meta_data/scanobjectnn/xyz_label.npy
  clip_feat_path: ReConV2/data/openshape/meta_data/scanobjectnn/cat_name_pt_feat.npy
  num_workers: 8
  batch_size: 128
  ratio: 0.3

npoints: 10000
total_bs: 256
step_per_update: 1
max_epoch: 200
