optimizer:
  type: AdamW
  kwargs:
    lr: 0.0001
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 300
    initial_epochs: 10

dataset:
  train:
    _base_: ReConV2/cfgs/dataset_configs/Hybrid.yaml
    others:
      subset: 'train'
      npoints: 1024
      whole: TRUE
      using_saved_features: TRUE

model:
  NAME: ReCon2
  group_size: 32
  num_group: 64
  mask_ratio: 0.7
  mask_type: causal
  embed_dim: 768
  depth: 12
  drop_path_rate: 0.1
  num_heads: 12
  decoder_depth: 4
  with_color: FALSE
  img_queries: 8
  text_queries: 3
  pretrained_model_name: 'vit_base_patch32_clip_224.openai'

npoints: 1024
total_bs: 256
step_per_update: 1
max_epoch: 300
