optimizer:
  type: AdamW
  kwargs:
    lr: 1e-4
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 100
    initial_epochs: 10

dataset:
  train:
    _base_: ReConV2/cfgs/dataset_configs/HybridLabeled.yaml
    others:
      subset: train
      npoints: 1024
  val:
    _base_: ReConV2/cfgs/dataset_configs/HybridLabeled.yaml
    others:
      subset: test
      npoints: 1024

model:
  NAME: PointTransformer
  embed_dim: 768
  depth: 12
  drop_path_rate: 0.2
  cls_dim: 87
  num_heads: 12
  group_size: 32
  num_group: 64
  with_color: False
  large_embedding: True
  img_queries: 10
  text_queries: 1
  decoder_depth: 4


npoints: 1024
total_bs: 128
step_per_update: 1
max_epoch: 100
grad_norm_clip: 10
